<?xml version="1.0" ?>
<robot name="sweeper" 
  xmlns:xacro="http://ros.org/wiki/xacro">
  
  <xacro:include filename="$(find custom_description)/description/lidar.urdf.xacro" />
  <xacro:include filename="$(find custom_description)/description/sweeper/urdf/sweeper_base_gazebo.urdf.xacro" />
  <xacro:include filename="$(find custom_description)/description/range_sensor.urdf.xacro" />
  <xacro:include filename="$(find custom_description)/description/kinect.urdf.xacro" />
  <xacro:property name="PI" value="3.1415926535897931" />
  <xacro:macro name="sweeper_wheel" params="prefix y_offset wheel_radius wheel_width">
    <link name="${prefix}_wheel_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="0.01" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        <material name="material">
          <color rgba="0.635 0.800 0.754 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        
      </collision>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <origin xyz="0 ${y_offset} 0.015" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="${prefix}_wheel_link" />
      <axis xyz="0 1 0" />
    </joint>
  </xacro:macro>
  <xacro:macro name="sweeper_base" params="diffdrive_update_rate:=40 wheel_separation wheel_radius:=0.036 wheel_width:=0.024 wheel_torque:=1.0 wheel_accel:=1.8 mass_kg:=3.5 base_diameter">
    <link name="base_footprint">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
        <material name="Green" />
      </visual>
      <collision>
        <origin xyz="0 0 0.017" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
      </collision>
    </link>
    <link name="base_link">
      <inertial>
        <origin xyz="0.01 0 0" />
        <mass value="2.4" />
        <inertia ixx="0.019995" ixy="0.0" ixz="0.0" iyy="0.019995" iyz="0.0" izz="0.03675" />
      </inertial>
      <visual>
        <origin xyz=" 0 0 0.0308" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://custom_description/description/sweeper/meshes/car1.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.48 0 0.58" rpy="0 0 0" />
        <geometry>
          <box size="1.852 1.559 1.2" />
        </geometry>
      </collision>
    </link>
    <link name="left_cliff_sensor_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>
    <link name="right_cliff_sensor_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>
    <link name="front_cliff_sensor_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>
    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 0.017" rpy="0 0 0" />
      <parent link="base_footprint" />
      <child link="base_link" />
    </joint>
    <joint name="base_left_cliff_sensor_joint" type="fixed">
      <origin xyz="0.07 0.14 0.01" rpy="0 ${PI/2} 0" />
      <parent link="base_link" />
      <child link="left_cliff_sensor_link" />
    </joint>
    <joint name="base_right_cliff_sensor_joint" type="fixed">
      <origin xyz="0.07 -0.14 0.01" rpy="0 ${PI/2} 0" />
      <parent link="base_link" />
      <child link="right_cliff_sensor_link" />
    </joint>
    <joint name="base_front_cliff_sensor_joint" type="fixed">
      <origin xyz="0.15 0.0 0.01" rpy="0 ${PI/2} 0" />
      <parent link="base_link" />
      <child link="front_cliff_sensor_link" />
    </joint>
    <xacro:sweeper_wheel prefix="left" y_offset="${wheel_separation / 2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>
    <xacro:sweeper_wheel prefix="right" y_offset="${wheel_separation / -2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>
    <!--<link name="rear_wheel_link"><inertial><origin xyz="0 0 0"/><mass value="0.001" /><inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001" /></inertial><visual><origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/><geometry><sphere radius="0.015" /></geometry></visual><collision><origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" /><geometry><sphere radius="0.015" /></geometry></collision></link><joint name="rear_castor_joint" type="fixed"><origin xyz="-0.13 0 0.0" rpy="0 0 0"/><parent link="base_link"/><child link="rear_wheel_link"/><axis xyz="0 1 0"/></joint>-->
    <link name="front_wheel_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="1" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
        <geometry>
          <sphere radius="0.1" />
        </geometry>
        <material name="material">
          <color rgba="0.635 0.800 0.754 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
        <geometry>
          <sphere radius="0.10" />
        </geometry>
      </collision>
    </link>
    <!-- fixed because there's no transmission -->
    <joint name="front_castor_joint" type="fixed">
      <origin xyz="1.14 0 0.0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="front_wheel_link" />
      <axis xyz="0 1 0" />
    </joint>
    <joint name="gyro_joint" type="fixed">
      <axis xyz="0 1 0" />
      <origin xyz="0 0 0.04" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="gyro_link" />
    </joint>
    <link name="gyro_link">
      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001" />
      </inertial>
    </link>
    <!-- Simulation sensors -->
    <sim_sweeper_base/>
  </xacro:macro>
</robot>