<?xml version="1.0" ?>
<robot 
  xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="sim_sweeper_base">
    <gazebo reference="base_link">
      <mu1>0.3</mu1>
      <mu2>0.3</mu2>
      <sensor type="contact" name="bumpers">
        <always_on>1</always_on>
        <update_rate>50.0</update_rate>
        <visualize>true</visualize>
        <contact>
          <collision>base_footprint_collision_base_link</collision>
        </contact>
      </sensor>
    </gazebo>
    <gazebo reference="left_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
    </gazebo>
    <gazebo reference="right_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
    </gazebo>
    <!--<gazebo reference="rear_wheel_link"><mu1>0.0</mu1><mu2>0.0</mu2><kp>1000000.0</kp><kd>100.0</kd><minDepth>0.001</minDepth><maxVel>1.0</maxVel></gazebo>-->
    <gazebo reference="front_wheel_link">
      <mu1>0.0</mu1>
      <mu2>0.0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
    </gazebo>
    <gazebo reference="gyro_link">
      <sensor type="imu" name="imu">
        <always_on>true</always_on>
        <update_rate>50</update_rate>
        <visualize>false</visualize>
        <imu>
          <noise>
            <type>gaussian</type>
            <rate>
              <mean>0.0</mean>
              <stddev>${0.0017*0.0017}</stddev>
              <!-- 0.25 x 0.25 (deg/s) -->
              <bias_mean>0.0</bias_mean>
              <bias_stddev>0.0</bias_stddev>
            </rate>
            <accel>
              <!-- not used in the plugin and real robot, hence using tutorial values -->
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </accel>
          </noise>
        </imu>
      </sensor>
    </gazebo>
    <gazebo reference="left_cliff_sensor_link">
      <sensor type="ray" name="left_cliff_sensor">
        <always_on>true</always_on>
        <update_rate>20.0</update_rate>
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <ray>
          <scan>
            <horizontal>
              <samples>1</samples>
              <resolution>1</resolution>
              <min_angle>0</min_angle>
              <max_angle>0</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.01</min>
            <max>0.04</max>
            <resolution>0.1</resolution>
          </range>
        </ray>
      </sensor>
    </gazebo>
    <gazebo reference="right_cliff_sensor_link">
      <sensor type="ray" name="right_cliff_sensor">
        <always_on>true</always_on>
        <update_rate>20.0</update_rate>
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <ray>
          <scan>
            <horizontal>
              <samples>1</samples>
              <resolution>1</resolution>
              <min_angle>0</min_angle>
              <max_angle>0</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.01</min>
            <max>0.04</max>
            <resolution>0.1</resolution>
          </range>
        </ray>
      </sensor>
    </gazebo>
    <gazebo reference="front_cliff_sensor_link">
      <sensor type="ray" name="front_cliff_sensor">
        <always_on>true</always_on>
        <update_rate>20.0</update_rate>
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <ray>
          <scan>
            <horizontal>
              <samples>1</samples>
              <resolution>1</resolution>
              <min_angle>0</min_angle>
              <max_angle>0</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.01</min>
            <max>0.04</max>
            <resolution>0.1</resolution>
          </range>
        </ray>
      </sensor>
    </gazebo>
    <gazebo>
      <plugin name="sweeper_controller" filename="libgazebo_ros_kobuki.so">
        <publish_tf>1</publish_tf>
        <left_wheel_joint_name>left_wheel_joint</left_wheel_joint_name>
        <right_wheel_joint_name>right_wheel_joint</right_wheel_joint_name>
        <wheel_separation>${wheel_separation}</wheel_separation>
        <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
        <torque>1</torque>
        <velocity_command_timeout>1</velocity_command_timeout>
        <cliff_sensor_left_name>left_cliff_sensor</cliff_sensor_left_name>
        <cliff_sensor_center_name>front_cliff_sensor</cliff_sensor_center_name>
        <cliff_sensor_right_name>right_cliff_sensor</cliff_sensor_right_name>
        <cliff_detection_threshold>0.04</cliff_detection_threshold>
        <bumper_name>bumpers</bumper_name>
        <imu_name>imu</imu_name>
      </plugin>
      <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>100.0</updateRate>
        <bodyName>base_link</bodyName>
        <topicName>simple_controller/absolute_position</topicName>
        <gaussianNoise>0</gaussianNoise>
        <frameName>map</frameName>
        <xyzOffsets>0 0 0</xyzOffsets>
        <rpyOffsets>0 0 0</rpyOffsets>
        <!--<interface:position name="p3d_base_position"/>-->
      </plugin>
    </gazebo>
  </xacro:macro>
</robot>